### ISSUE TITLE
fonts.gstatic.com在中国大陆受到DNS污染及SNI阻断

### ISSUE THREAD

**Issue by BnqDzj** [ImYrS/aliyundrive-pro-home#11]
fonts.gstatic.com在中国大陆受到DNS污染及SNI阻断
表现为全部TIMEOUT或被RST
![image](https://github.com/ImYrS/aliyundrive-pro-home/assets/64721413/fc208cdc-aab8-439e-8cc7-4ed74e68b1cb)

**Comment by BnqDzj** [comment]
ajax.googleapis.com - 前端公共库，替换为 ajax.loli.net
fonts.googleapis.com - 免费字体库，替换为 fonts.googleapis.cn
themes.googleusercontent.com - fonts 有时会使用到这个里面的资源，替换为 themes.loli.net
fonts.gstatic.com - 免费字体库，替换为 fonts.gstatic.cn
www.google.com/recaptcha - Google 图像验证库，替换为 www.recaptcha.net/recaptcha
secure.gravatar.com - gravatar 头像，替换为 gravatar.loli.net
maxcdn.bootstrapcdn.com/bootstrap - bootstrap 框架使用的 CDN，替换为 lib.baomitu.com/twitter-bootstrap/
code.jquery.com/jquery-(version)(suffix) - jquery 框架使用的 CDN，替换为 lib.baomitu.com/jquery/$verson/$suffix
cdnjs.cloudflare.com - 替换为 cdnjs.loli.net 
cdn.jsdelivr.net - 替换为 fastly.jsdelivr.net
developers.google.com - 替换为 developers.google.cn
developer.android.com - 替换为 developer.android.google.cn
source.android.com - 替换为 source.android.google.cn
www.gstatic.com - 替换为 www.gstatic.cn

**Comment by BnqDzj** [comment]
有的可能失效了

**Comment by ImYrS** [comment]
已修复, 受 CDN 及浏览器缓存影响, 可能需要一定时间生效
