### ISSUE TITLE
自定义代理功能能否采用Xray？

### ISSUE THREAD

**Issue by BnqDzj** [ImYrS/aliyundrive-pro-home#12]
https://xtls.github.io/
Xray可以通过不同的UUID来区分用户，为不同的用户采用不同的Xray配置
Xray支持很多出站协议
Blackhole，DNS，Freedom，HTTP，Shadowsocks，Socks，Trojan，VLESS，VMess，Wireguard

**Comment by ImYrS** [comment]
@BnqDzj 我认为这有些大炮打蚊子的意思, 需要额外配置, 而且支持 xray 的代理节点一般都部署在海外范围, 并不适合作为本项目签到的代理 IP 使用.
