### ISSUE TITLE
备份任务1T没成功且无法释放空间

### ISSUE THREAD

**Issue by BJAny** [ImYrS/aliyundrive-pro-home#17]
备份任务已经有1t的占用空间了，但是在相册里面找不到任何文件，然后任务也没有成功备份，现在就是吃了1t但是找不到任何文件能删除释放。
![image](https://github.com/ImYrS/aliyundrive-pro-home/assets/6690619/69b9cf27-9e7d-4f12-b3de-ebd286a96350)
![image](https://github.com/ImYrS/aliyundrive-pro-home/assets/6690619/2bc72651-56f2-48e6-a18f-6a36c1dff433)
![image](https://github.com/ImYrS/aliyundrive-pro-home/assets/6690619/794ced1b-ecdf-47bb-9e25-9eb9d5932f4f)
![image](https://github.com/ImYrS/aliyundrive-pro-home/assets/6690619/bf50a26a-0f35-456a-b417-066c4e6bd428)

**Comment by ImYrS** [comment]
@BJAny 备份盘 -> 相册, 在设备备份相册中

**Comment by BJAny** [comment]
刚才看过了，也没有，然后我删了设备

> @BJAny 备份盘 -> 相册, 在设备备份相册中

**Comment by ImYrS** [comment]
@BJAny 删除设备不能移除备份文件, 加一下交流群反馈情况

**Comment by BJAny** [comment]
群号是啥

> @BJAny 删除设备不能移除备份文件, 加一下交流群反馈情况

**Comment by BJAny** [comment]
哦看到了
