### ISSUE TITLE
推送渠道的pushplus没有了

### ISSUE THREAD

**Issue by YJLX-dmj** [ImYrS/aliyundrive-pro-home#19]
推送渠道的pushplus怎么没有了？以前有的这两天不推送了删除之后发现没有了
![QQ截图20230818105809](https://github.com/ImYrS/aliyundrive-pro-home/assets/69313368/775a9358-d300-4e2c-a83c-d47d955cf4f1)

**Comment by ImYrS** [comment]
@YJLX-dmj https://t.me/aliyun_auto_signin/12138

**Comment by YJLX-dmj** [comment]
知道了
